DinnersAccounting/UI/Controllers/BalanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA.Dinners.Domain;
using DA.Dinners.Domain.Abstract;

namespace UI.Controllers
{
    [Authorize]
    public class BalanceController : Controller
    {
        private readonly IPersonRepository personRepository;

        public BalanceController(IPersonRepository personRepository)
        {
            this.personRepository = personRepository;
        }

        public ActionResult Index()
        {
            Person person = personRepository.All.SingleOrDefault( p => p.DomainName == User.Identity.Name);
            
            return View(person);
        }

        public ActionResult AdminOperations()
        {
            return View(personRepository.All);
        }
    }
}

DinnersAccounting/UI/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA.Dinners.Domain.Abstract;

namespace UI.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderRepository orderRepository;

        public OrdersController(IOrderRepository orderRepository)
        {
            this.orderRepository = orderRepository;
        }

        public ActionResult OrdersAccounting()
        {
            return View();
        }

    }
}

DinnersAccounting/UI/Controllers/PropositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA.Dinners.Domain.Concrete;
using DA.Dinners.Model;
using UI.Models;
using DA.Dinners.Domain.Abstract;

namespace UI.Controllers
{
    public class PropositionsController : Controller
    {
        //
        // GET: /Proposition/

        //private readonly IPropositionRepository propositionRepository;
        private readonly IContinuousPropositionRepository continuousPropositionRepository;


        public PropositionsController(IPropositionRepository propositionRepository, IContinuousPropositionRepository continuousPropositionRepository)
        {
            //this.propositionRepository = propositionRepository;
            this.continuousPropositionRepository = continuousPropositionRepository;
        }

        public ActionResult Admin()
        {
            return View();
        }

        public ActionResult User()
        {
            return View();
        }
    }
}

DinnersAccounting/UI/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Css/Styles.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.19.custom.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <link href= "@Url.Content("~/Scripts/niceforms-default.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            if (typeof PageScript == 'function') {
                PageScript();
            }
        });
    </script>
    <div class="page">
        <header id="header">
            <div id="title">
                <h1>
                    Yidalnya</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <br />
            <nav>
                <ul id="navlist">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Баланс", "Index", "Balance")</li>
                    <li>@Html.ActionLink("Информация о пользователе", "GetMyInfo", "Home")</li>
                    <li>@Html.ActionLink("Меню", "User", "Propositions")</li>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Управление меню", "Admin", "Propositions")</li>
                        <li>@Html.ActionLink("Операции со счётом", "AdminOperations", "Balance")</li>
                        <li>@Html.ActionLink("Заказы", "OrdersAccounting", "Orders")</li>
                    }
                </ul>
            </nav>
        </header>
        <section>
            <div id="main">
                @RenderBody()
            </div>
        </section>
        <footer>
            <small>All rights reserved. ©Copyright @DateTime.Now.Year, DataArt Corp.</small>
        </footer>
    </div>
</body>
</html>

DinnersAccounting/UI/Views/Shared/_LogOnPartial.cshtml
@{
    if (this.User.Identity.IsAuthenticated)
    {
    <text>Welcome <strong>@User.Identity.Name</strong>! | @Html.ActionLink("Выйти", "LogOut", "Account", new { returnUrl = Context.Request.Url }, null)</text><br />
    }
    else
    {
    @Html.ActionLink("Войти", "LogOn", "Account", new { returnUrl = Context.Request.Url }, null)
    }

}